# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import grtest_pb2 as grtest__pb2


class TestServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.PingRequest = channel.unary_unary(
        '/TestService/PingRequest',
        request_serializer=grtest__pb2.Ping.SerializeToString,
        response_deserializer=grtest__pb2.Pong.FromString,
        )
    self.Stream = channel.unary_stream(
        '/TestService/Stream',
        request_serializer=grtest__pb2.Ping.SerializeToString,
        response_deserializer=grtest__pb2.Pong.FromString,
        )


class TestServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def PingRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Stream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TestServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'PingRequest': grpc.unary_unary_rpc_method_handler(
          servicer.PingRequest,
          request_deserializer=grtest__pb2.Ping.FromString,
          response_serializer=grtest__pb2.Pong.SerializeToString,
      ),
      'Stream': grpc.unary_stream_rpc_method_handler(
          servicer.Stream,
          request_deserializer=grtest__pb2.Ping.FromString,
          response_serializer=grtest__pb2.Pong.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'TestService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
